"""Añadir columna Total en venta

Revision ID: 2b9eeea56b0d
Revises: 7dd78d76aa8d
Create Date: 2024-12-15 20:58:46.866549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9eeea56b0d'
down_revision = '7dd78d76aa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.drop_column('Total')

    # ### end Alembic commands ###
