"""Actualizar columna Cliente_ID a nullable true en Venta 

Revision ID: 67e4d31e03d4
Revises: ed56babdc701
Create Date: 2025-02-04 23:52:20.936741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '67e4d31e03d4'
down_revision = 'ed56babdc701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.alter_column('Cliente_ID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.alter_column('Cliente_ID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
