"""Añadir columna subTotal en detalleVenta

Revision ID: 7dd78d76aa8d
Revises: c8d143d78d06
Create Date: 2024-12-15 19:41:25.716458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '7dd78d76aa8d'
down_revision = 'c8d143d78d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('DetalleVenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SubTotal', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DetalleVenta', schema=None) as batch_op:
        batch_op.drop_column('SubTotal')

    # ### end Alembic commands ###
