"""Añadir columna CodigoBarras a Producto

Revision ID: c8d143d78d06
Revises: 
Create Date: 2024-12-09 02:17:11.070254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c8d143d78d06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CodigoBarras', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.drop_column('CodigoBarras')

    # ### end Alembic commands ###
