"""Permitir valores negativos en Stock

Revision ID: d5c24728b55c
Revises: 67e4d31e03d4
Create Date: 2025-02-07 13:24:05.440817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c24728b55c'
down_revision = '67e4d31e03d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.alter_column('Stock',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Producto', schema=None) as batch_op:
        batch_op.alter_column('Stock',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
