"""Añadir columna TipoVenta, DatosDocumentoVenta, TipoPago, DatosPago  en Venta

Revision ID: ed56babdc701
Revises: 2b9eeea56b0d
Create Date: 2025-02-04 20:49:55.606907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed56babdc701'
down_revision = '2b9eeea56b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TipoVenta', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('DatosDocumentoVenta', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('TipoPago', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('DatosPago', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venta', schema=None) as batch_op:
        batch_op.drop_column('DatosPago')
        batch_op.drop_column('TipoPago')
        batch_op.drop_column('DatosDocumentoVenta')
        batch_op.drop_column('TipoVenta')

